### ISSUE TITLE
writing-a-model.ipynb not working on Windows

### ISSUE THREAD

**Issue by chonlei** [pints-team/pints#113]
Just tested it again. All examples work except `writing-a-model.ipynb`! This is what the output looks like 

![image](https://user-images.githubusercontent.com/26725646/33554144-78c69174-d8f3-11e7-9033-9365009f260a.png)

I guess, this is quite an issue if `toy.LogisticModel()` works but self defined model does not.

**Comment by chonlei** [comment]
Just did a few more test. It seems like our MCMC routine works perfectly fine -- but CMAES and SNES, which use `pickle` and `multiprocessing`, are not compatible with it. 

Any thoughts? If this is users' problem then close this issue, if not, then we probably want to add a note on this potential problem. I guess Windows anaconda users would not be the minority.

**Comment by MichaelClerx** [comment]
The relevant note is here: http://pints.readthedocs.io/en/latest/function_evaluation.html?highlight=evaluator#pints.ParallelEvaluator

This is an issue with parallelisation on Windows, will do some googling to see if there's an easy fix for it in the examples...

**Comment by chonlei** [comment]
More error output if it helps to decide is it users' problem or something we should step into.
```
Run 1: population size 8
(4_w,8)-aCMA-ES (mu_w=2.6,w_1=52%) in dimension 2 (seed=526419, Mon Dec 04 13:16:01 2017)
Traceback (most recent call last):

  File "<ipython-input-9-e03f19ad2d37>", line 1, in <module>
    runfile('C:/Users/cholei/Desktop/test.py', wdir='C:/Users/cholei/Desktop')

  File "C:\ProgramData\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 86, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/cholei/Desktop/test.py", line 31, in <module>
    sigma0,

  File "c:\users\cholei\documents\git\pints\pints\_optimisers\_cmaes.py", line 152, in cmaes
    return CMAES(function, boundaries, x0, sigma0).run()

  File "c:\users\cholei\documents\git\pints\pints\_optimisers\_cmaes.py", line 127, in run
    es.tell(candidates, evaluator.evaluate(candidates))

  File "c:\users\cholei\documents\git\pints\pints\_evaluation.py", line 82, in evaluate
    return self._evaluate(positions)

  File "c:\users\cholei\documents\git\pints\pints\_evaluation.py", line 221, in _evaluate
    self._populate()

  File "c:\users\cholei\documents\git\pints\pints\_evaluation.py", line 208, in _populate
    w.start()

  File "C:\ProgramData\Anaconda2\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)

  File "C:\ProgramData\Anaconda2\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)

  File "C:\ProgramData\Anaconda2\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 224, in dump
    self.save(obj)

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 425, in save_reduce
    save(state)

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 687, in _batch_setitems
    save(v)

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 425, in save_reduce
    save(state)

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 687, in _batch_setitems
    save(v)

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 425, in save_reduce
    save(state)

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 687, in _batch_setitems
    save(v)

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 425, in save_reduce
    save(state)

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 568, in save_tuple
    save(element)

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self

  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 492, in save_string
    self.write(BINSTRING + pack("<i", n) + obj)

IOError: [Errno 22] Invalid argument
```
This the output when I just copy the example to `Spyder` and run.

**Comment by MichaelClerx** [comment]
Can you try sticking the lines that run the optimisation inside an `if __name__ == '__main__'` statement?

https://stackoverflow.com/questions/37103243/multiprocessing-pool-in-jupyter-notebook-works-on-linux-but-not-windows#41294640

**Comment by MichaelClerx** [comment]
@chonlei any updates?

**Comment by chonlei** [comment]
Not working either, tried putting just the run line which gives error and the whole script (except `from __future__ import ...`) under `if __name__ == '__main__':`, but both give the same error as above. 

I think another odd thing is it works perfectly fine with toy models defined in `pints.toy`...

**Comment by chonlei** [comment]
Just sorted out the problem and solution for it... Note that it just does not work with jupyter notebook (or iPython in gerenal) in Windows if we define a user model class. See:

https://github.com/ContinuumIO/anaconda-issues/issues/7633

I will turn the writing-a-model example into a Python script example for Windows user to get away the multiprocessing or fork() problem. Following this:

https://docs.python.org/2/library/multiprocessing.html#windows

**Comment by MichaelClerx** [comment]
I was working towards that same conclusion: https://bugs.python.org/issue5509

Maybe we should just avoid having parallelism in the example instead

**Comment by chonlei** [comment]
I have created a .py file that does the same thing as the writing-a-model.ipynb which works for Windows. I think it is better to have that, in case Windows users want to do parallelisation for the optimisation problems (or even some inference tools).

**Comment by chonlei** [comment]
And maybe also add a line in the writing-a-model.ipynb example to explain either switch off the parallelisation or see the *writing-a-model-for-Windows.py* for parallelisation. 

Should I create a PR for that?

**Comment by MichaelClerx** [comment]
It's currently not possible to disable parallelisation, but this will be added in #198 . I've added a commit there that addresses this problem!

**Comment by MichaelClerx** [comment]
Update:

- Parallellisation is now switched off by default, which is a good idea for all demos etc. because it's less likely to go wrong!
- We should have an example that uses it (I think we do)
- It's also important to notice that, for our toy problems _parallelising slows things down_ . This is because they are simple problems, that evaluate incredibly quickly, so that parallelising the problem evaluation (which is what we do, the methods themselves are not parallelised) is not helpful, and the overhead of multiprocessing just slows us down. For real problems this is not the case! E.g. Fitting on Kylie's sine wave experiment runs much faster in parallel than sequentially, even though this is a 2 state model and so pretty much as simple as you're going to find in comp.biol.
