### ISSUE TITLE
Divide-by-zero in highdimensionallgaussian if dimensions=1

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1236]
```
Traceback (most recent call last):
  File "./popmcmc.py", line 10, in <module>
    log_pdf = pints.toy.HighDimensionalGaussianLogPDF(dimension=1)
  File "/home/michael/dev/pints/pints/toy/_high_dimensional_gaussian.py", line 41, in __init__
    if rho < -float(1.0 / (self._n_parameters - 1)):
ZeroDivisionError: float division by zero
```

Needs either a fix or an error saying it can't be 1

**Comment by ben18785** [comment]
Closed by #1268
