### ISSUE TITLE
Stan interface notebook is broken

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1448]
Couple of warnings, then an error when building

```
Building: 32.0s, done.Messages from stanc:
Warning in \'/tmp/httpstan_ioc8i20p/model_vdpin3fp.stan\', line 4, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in \'/tmp/httpstan_ioc8i20p/model_vdpin3fp.stan\', line 11, column 17: A
    normal distribution is given parameter sigma as a scale parameter
    (argument 2), but sigma was not constrained to be strictly positive.
Warning: The parameter sigma has no priors.
Warning: The parameter mu has no priors.

Error handling request

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/httpstan/views.py", line 253, in handle_show_params
    services_module = httpstan.models.import_services_extension_module(model_name)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/httpstan/models.py", line 90, in import_services_extension_module
    module: ModuleType = importlib.util.module_from_spec(spec)  # type: ignore
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: /home/runner/.cache/httpstan/4.7.2/models/vdpin3fp/stan_services_model_vdpin3fp.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv

Traceback (most recent call last):
  File "<string>", line 67, in <module>
  File "/home/runner/work/pints/pints/pints/interfaces/stan/_stan.py", line 67, in __init__
    posterior = stan.build(code, data=data)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/stan/model.py", line 517, in build
    return asyncio.run(go())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/stan/model.py", line 509, in go
    raise RuntimeError(resp.json()["message"])
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/stan/common.py", line 24, in json
    return simdjson.loads(self.content)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/simdjson/__init__.py", line 61, in loads
    return parser.parse(s, True)
ValueError: The JSON document has an improper structure: missing or superfluous commas, braces, missing keys, etc.
```

**Comment by MichaelClerx** [comment]
This was something to do with Github actions switching to 3.10 before the stan team were quite ready for it.
The error has disappeared now: https://github.com/pints-team/pints/actions/workflows/notebook-interfaces-test.yml
