### ISSUE TITLE
CMAES Can have indefinite matrix issues during run, raises ValueError

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#247]
```
Traceback (most recent call last):
  File "./fit.py", line 187, in <module>
    p, s = opt.run()
  File "/home/michael/dev/pints/pints/_optimisers/__init__.py", line 320, in run
    xs = self._optimiser.ask()
  File "/home/michael/dev/pints/pints/_optimisers/_cmaes.py", line 58, in ask
    self._xs = np.array(self._es.ask())
  File "/home/michael/.local/lib/python2.7/site-packages/cma/evolution_strategy.py", line 1694, in ask
    pop_geno = self.ask_geno(number, xmean, sigma_fac)
  File "/home/michael/.local/lib/python2.7/site-packages/cma/evolution_strategy.py", line 1959, in ask_geno
    ary = self.sigma_vec * np.asarray(self.sm.sample(Niid))
  File "/home/michael/.local/lib/python2.7/site-packages/cma/sampler.py", line 222, in sample
    self.update_now(lazy_update_gap)
  File "/home/michael/.local/lib/python2.7/site-packages/cma/sampler.py", line 293, in update_now
    self._decompose_C()
  File "/home/michael/.local/lib/python2.7/site-packages/cma/sampler.py", line 342, in _decompose_C
    " this must be considered as a bug")
ValueError: covariance matrix was not positive definite, this must be considered as a bug
```

Could be that we're getting a warning about this but not handling it correctly? Will have to check if we're using cma-es's ask-and-tell correctly now that we're avoiding `stop()` !

**Comment by MichaelClerx** [comment]
Guessing the correct behaviour here would be to terminate the optimisation, since the method got stuck somehow? If so, we'd have to update the interfaces slightly so that this is allowed.

**Comment by mirams** [comment]
We aren't letting it see -inf likelihoods are we?

**Comment by MichaelClerx** [comment]
That could also be a thing! Will look into this soon!

**Comment by MichaelClerx** [comment]
(Which will mean setting up some more logging / debug output stuff in Pints first, I think)

**Comment by MichaelClerx** [comment]
Seems @martinjrobins has been seeing this error with the HH IK model too

**Comment by MichaelClerx** [comment]
> We aren't letting it see -inf likelihoods are we?
Checked it: Nope!
