### ISSUE TITLE
bug in functional testing filename generation-parsing

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#526]
The functional testing can create filenames such as:

`opt_logistic_PSO-2018-09-30-14:00:09-2.txt`

which generate the following error:
```
Traceback (most recent call last):
  File "./funk", line 13, in <module>
    main()
  File "/scratch/robinsonm/git/functional-testing/pfunk/__main__.py", line 240, in main
    args.func(args)
  File "/scratch/robinsonm/git/functional-testing/pfunk/__main__.py", line 22, in list_tests
    dates = pfunk.find_test_dates()
  File "/scratch/robinsonm/git/functional-testing/pfunk/_io.py", line 358, in find_test_dates
    date = time.strptime(date, pfunk.DATE_FORMAT)
  File "/scratch/robinsonm/miniconda3/lib/python3.6/_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/scratch/robinsonm/miniconda3/lib/python3.6/_strptime.py", line 365, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: -2
```

**Comment by martinjrobins** [comment]
fixed
