### ISSUE TITLE
FC for nested samplers is failing

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#798]
```
ERROR:pfunk._test:Exception in test: nested_egg_box_NestedRejectionSampler
Running test nested_egg_box_NestedRejectionSampler
Traceback (most recent call last):
  File "./funk", line 13, in <module>
    main()
  File "/home/pints/functional-testing/pfunk/__main__.py", line 304, in main
    args.func(args)
  File "/home/pints/functional-testing/pfunk/__main__.py", line 76, in run
    pfunk.tests.run(name)
  File "/home/pints/functional-testing/pfunk/tests/_tests.py", line 28, in run
    _tests[name].run()
  File "/home/pints/functional-testing/pfunk/_test.py", line 221, in run
    self._run(w, log_path)
  File "/home/pints/functional-testing/pfunk/tests/nested_egg_box.py", line 65, in _run
    log_prior = pints.MultivariateNormalLogPrior(
AttributeError: module 'pints' has no attribute 'MultivariateNormalLogPrior'
```

**Comment by MichaelClerx** [comment]
Thanks @fcooper8472 !
