### ISSUE TITLE
Functional testing failures due to "no attribute 'kl_score'"

### ISSUE THREAD

**Issue by fcooper8472** [pints-team/pints#807]
See, e.g.:
```
[command]/bin/bash --noprofile --norc /home/pints/azure-devops/pints-skip/_work/_temp/e87d6a54-f757-4d1d-893b-9d6221c17a55.sh
ERROR:pfunk._test:Exception in test: nested_egg_box_NestedEllipsoidSampler
Refreshing Pints repository
Running test nested_egg_box_NestedEllipsoidSampler
Traceback (most recent call last):
  File "./funk", line 14, in <module>
    main()
  File "/home/pints/functional-testing/pfunk/__main__.py", line 485, in main
    args.func(args)
  File "/home/pints/functional-testing/pfunk/__main__.py", line 109, in run
    pfunk.tests.run(name)
  File "/home/pints/functional-testing/pfunk/tests/_tests.py", line 28, in run
    _tests[name].run()
  File "/home/pints/functional-testing/pfunk/_test.py", line 218, in run
    self._run(w, log_path)
  File "/home/pints/functional-testing/pfunk/tests/nested_egg_box.py", line 90, in _run
    log_pdf.kl_score(samples[i:i + n_window]) for i in iters]
  File "/home/pints/functional-testing/pfunk/tests/nested_egg_box.py", line 90, in <listcomp>
    log_pdf.kl_score(samples[i:i + n_window]) for i in iters]
AttributeError: 'SimpleEggBoxLogPDF' object has no attribute 'kl_score'
```

**Comment by MichaelClerx** [comment]
Should be fixed now
