### ISSUE TITLE
Error in toy annulus notebook

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#974]
```
Running...
Done!
Running...
Using Hamiltonian Monte Carlo
Generating 4 chains.
Running in sequential mode.
Iter. Eval. Accept.   Accept.   Accept.   Accept.   Time m:s
0     4      0         0         0         0          0:00.0
1     84     0.333     0.333     0.333     0.333      0:00.0
2     164    0.5       0.5       0.5       0.5        0:00.0
3     244    0.6       0.6       0.6       0.6        0:00.1
20    1604   0.909     0.909     0.864     0.909      0:00.3
40    3204   0.952381  0.952381  0.929     0.952381   0:00.6
60    4804   0.968     0.968     0.952     0.968      0:00.8
80    6404   0.976     0.976     0.963     0.976      0:01.1
100   8004   0.98      0.98      0.971     0.98       0:01.3
120   9604   0.984     0.984     0.975     0.984      0:01.6
140   11204  0.986     0.986     0.971831  0.986      0:01.8
160   12804  0.988     0.988     0.975     0.988      0:02.1
180   14404  0.989011  0.989011  0.978022  0.989011   0:02.3
200   16004  0.990099  0.990099  0.980198  0.990099   0:02.6
220   17604  0.990991  0.990991  0.977     0.990991   0:02.8
240   19204  0.992     0.992     0.979     0.992      0:03.1
260   20804  0.992     0.992     0.980916  0.992      0:03.3
280   22404  0.993     0.993     0.982     0.993      0:03.6
300   24004  0.993     0.993     0.983     0.99       0:03.8
320   25604  0.991     0.994     0.984472  0.991      0:04.1
340   27204  0.991     0.994152  0.985     0.991      0:04.3
360   28804  0.992     0.994     0.986     0.992      0:04.6
380   30404  0.992     0.992     0.986911  0.992      0:04.8
400   31924  0.993     0.993     0.988     0.993      0:05.1
Halting: Maximum number of iterations (400) reached.
Done!
Running...


-- stderr ---------------------------------------------------------------------

Traceback (most recent call last):
  File "<string>", line 165, in <module>
  File "/home/travis/build/pints-team/pints/pints/_mcmc/__init__.py", line 561, in run
    fxs = evaluator.evaluate(xs)
  File "/home/travis/build/pints-team/pints/pints/_evaluation.py", line 107, in evaluate
    return self._evaluate(positions)
  File "/home/travis/build/pints-team/pints/pints/_evaluation.py", line 399, in _evaluate
    scores[k] = self._function(x, *self._args)
  File "/home/travis/build/pints-team/pints/pints/toy/_annulus.py", line 61, in __call__
    if not len(x) == self._n_parameters:
TypeError: object of type \'NoneType\' has no len()
```

Came up in notebook testing

**Comment by MichaelClerx** [comment]
To test, use
```
./run-tests.py --debook examples/toy-distribution-annulus.ipynb test.py
```
and then the lines in `test.py` should match up with the error above

**Comment by MichaelClerx** [comment]
Minimal example to reproduce:

```
import pints
import pints.toy
import numpy as np
log_pdf = pints.toy.AnnulusLogPDF(dimensions=3, r0=20, sigma=0.5)
x0 = np.zeros(log_pdf.n_parameters()) + np.random.normal(0, 1, size=(4, log_pdf.n_parameters()))
mcmc = pints.MCMCController(log_pdf, 4, x0, method=pints.AdaptiveCovarianceMC)
mcmc.set_max_iterations(4000)
mcmc.set_log_to_screen(False)
chains = mcmc.run()
```

**Comment by MichaelClerx** [comment]
@ben18785 this is an interesting one!
We need some error to be raised if people try to use the AdaptiveCovarianceMC class directly!
